### ISSUE TITLE
add parent_id

### ISSUE THREAD

**Issue by nichtmax** [luto/autoputio#1]
it would be nice to be able to define the folder the transfers should end up in. [add_url](https://github.com/cenkalti/putio.py/blob/0adae34f812ed24b595128aec1ebbf6248d048aa/putiopy.py#L560) and [add_torrent](https://github.com/cenkalti/putio.py/blob/0adae34f812ed24b595128aec1ebbf6248d048aa/putiopy.py#L571) accept `parent_id` as second argument, if not set it's 0 - the root folder.

Each folder has a unique `parent_id`, maybe it's possible to look up the ID for the folder with [find](https://github.com/cenkalti/putio.py/blob/0adae34f812ed24b595128aec1ebbf6248d048aa/putiopy.py#L301).

A second argument would be nice: `python autoputio.py torrents [destination_folder| parent_id]`

**Comment by nichtmax** [comment]
There is an [endpoint in the API](https://app.swaggerhub.com/apis-docs/putio/putio/2.8.2#/) for looking up `parent_id` for files and folders.

**Comment by luto** [comment]
https://github.com/luto/autoputio/commit/a0acff110965ba2682ea3fae291440d7697390d9

give it a try. I don't have a putio account to test.
